---
- name: Bare Metal Setup Playbook
  hosts: sx-staging-app
  become: yes

  tasks:
    - name: Install git 2.25.1
      apt:
        name: git=1:2.25.1*
        update_cache: yes
        state: present

    - name: Install zsh 5.8
      apt:
        name: zsh=5.8*
        update_cache: yes
        state: present
        
    - name: Download oh-my-zsh
      shell: touch install.sh && curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh > install.sh && echo "\nexit" >> install.sh && chmod +x install.sh 
  
    - name: Install oh-my-zsh
      become: yes
      become_user: ubuntu
      expect:
        command: sh -c "RUNZSH=no ./install.sh" && rm install.sh
        responses:
          "~" : "exit\r"
  
    - name: Set ZSH as default shell for user ubuntu
      shell: 
        cmd: chsh -s $(which zsh) ubuntu
  
    - name: Setup remote sublime
      shell: |
        wget -O /usr/local/bin/subl \https://raw.github.com/aurora/rmate/master/rmate
        chmod a+x /usr/local/bin/subl

    - name: Install NPM 6.14.4
      apt:
        name: npm=6.14.4*
        state: present

    - name: Install n 8.2.0
      community.general.npm:
        name: n
        global: yes
        state: present
        version: '8.2.0'

    - name: Setup node version 16.15 using n version manager
      shell:
        cmd: n 16.15

    # -- DEPRECATED --
    # NGINX
    # Only for App Servers - not required for API servers

    # - name: Install certbot
    #   apt:
    #     name: certbot=0.40.0*
    #     state: present

    # - name: Install NGINX 1.18
    #   apt:
    #     name: nginx=1.18*
    #     state: present

    # - name: Copy NGINX conf
    #   ansible.builtin.copy:
    #     src: bare-metal/nginx-basic-http.conf
    #     dest: /etc/nginx/sites-available/base.conf

    # - name: Create NGINX symbolic link 
    #   file:
    #     src: "/etc/nginx/sites-available/base.conf"
    #     dest: "/etc/nginx/sites-enabled/base.conf"
    #     state: link

    # - name: Delete default NGINX conf
    #   file:
    #     state: absent
    #     path: /etc/nginx/sites-enabled/default

    # - name: Restart NGINX
    #   service: name=nginx state=restarted enabled=yes



