---
- name: Maintenance Playbook

  hosts: sx-staging

  become: yes
  vars:
    app_name: "api"
    # app_name: "admin"
    # app_name: "bulkupload"

  tasks:


    # - name: Install oh-my-zsh
    #   become: yes
    #   become_user: ubuntu
    #   expect:
    #     command: ls
    #     responses:
    #       "shell easier" : "2\r"
    #       # "~" : "exit\r"
    #   register: command_output
    # - debug:
    #     var: command_output.stdout_lines

    - name: Modifiy access permissions
      shell: |
        cd /home/ubuntu/
        chmod -R o-rwx ./*
        chmod -R o+rx ./scripts/
        cd /home/ubuntu/.pm2/logs
        chmod -R o+r ./*

    - name: Create Logging user
      shell: |
        groupadd logsonly
        useradd logger -G logsonly
        mkdir /home/logger
        mkdir /home/logger/.ssh

    - name: Add SSH key
      shell: |
        echo "ssh-ed25519 DFGXCHVJHBKJLNK onlylogger2@ABCD" > /home/logger/.ssh/authorized_keys
        echo "tail -f /home/ubuntu/.pm2/logs/{{ app_name }}.log & tail -f /home/ubuntu/.pm2/logs/{{ app_name }}-error.log" > /home/logger/run.sh
        chmod a+x /home/logger/run.sh 

    # - name: List
    #   become: yes
    #   become_user: ubuntu
    #   shell: |
    #     ls
    #   register: command_output
    # - debug:
    #     var: command_output.stdout

    # - name: List
    #   become: yes
    #   become_user: ubuntu
    #   shell: |
    #     sleep 10
    #     ls
    #   register: command_output
    # - debug:
    #     var: command_output.stdout

    # - name: Pull sx-static
    #   become: yes
    #   become_user: ubuntu
    #   shell: |
    #     cd /home/ubuntu/sx-static
    #     git pull
    #   register: command_output1
    # - debug:
    #     var: command_output1.stdout_lines

    # - name: Restart
    #   become: yes
    #   become_user: ubuntu
    #   shell: |
    #     pm2 restart all
    #     pm2 log --nostream
    #   register: command_output
    # - debug:
    #     var: command_output.stdout_lines



