---
- name: Maintenance Playbook

  hosts: sx-api*
  # hosts: sx-admin*

  become: yes
  vars:
    app_name: "api"
    # app_name: "admin"
    # app_name: "bulkupload"

  tasks:

    - name: Setup Logging user
      shell: |
        cd /home/ubuntu/
        chmod -R o-rwx ./*
        chmod -R o+rx ./scripts/
        cd /home/ubuntu/.pm2/logs
        chmod -R o+r ./*
        groupadd logsonly
        useradd logger -G logsonly
        mkdir /home/logger
        mkdir /home/logger/.ssh
        echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIB9/oHGG37SgvfdXCnpRfA7vuoHb5t7K+8R6Nn/I3PwZ onlylogger2@shyplite" > /home/logger/.ssh/authorized_keys
        echo "tail -f /home/ubuntu/.pm2/logs/{{ app_name }}.log & tail -f /home/ubuntu/.pm2/logs/{{ app_name }}-error.log" > /home/logger/run.sh

    # - name: List
    #   become: yes
    #   become_user: ubuntu
    #   shell: |
    #     pm2 list
    #   register: command_output
    # - debug:
    #     var: command_output.stdout_lines

    # - name: Pull sx-static
    #   become: yes
    #   become_user: ubuntu
    #   shell: |
    #     cd /home/ubuntu/sx-static
    #     git pull
    #   register: command_output1
    # - debug:
    #     var: command_output1.stdout_lines

    # - name: Restart
    #   become: yes
    #   become_user: ubuntu
    #   shell: |
    #     pm2 restart all
    #     pm2 log --nostream
    #   register: command_output
    # - debug:
    #     var: command_output.stdout_lines



