---
- name: NGINX Setup Playbook
  hosts: im-admin
  become: yes
  vars:
    server_type: "reverse-proxy"
    # server_type: "static-files"

  tasks:

    - name: Install certbot
      apt:
        name: certbot=0.40.0*
        state: present

    - name: Install certbot-nginx
      apt:
        name: python3-certbot-nginx
        state: present

    - name: Install NGINX 1.18
      apt:
        name: nginx=1.18*
        state: present

    - name: Copy NGINX conf - {{ server_type }}
      ansible.builtin.copy:
        src: bare-metal/nginx-{{ server_type }}-http.conf
        dest: /etc/nginx/sites-available/base.conf

    - name: Create NGINX symbolic link 
      file:
        src: "/etc/nginx/sites-available/base.conf"
        dest: "/etc/nginx/sites-enabled/base.conf"
        state: link

    - name: Delete default NGINX conf
      file:
        state: absent
        path: /etc/nginx/sites-enabled/default

    - name: Restart NGINX
      service: name=nginx state=restarted enabled=yes

    - name: Generate and Install certificate
      expect:
        command: certbot --nginx -d hq.importee.club
        responses:
          '"(used for urgent renewal and security notices)"' : "karan@shyplite.com\r"
          '"(A)gree/(C)ancel"' : "A\r"
          '"(Y)es/(N)o"' : "N\r"
          'Select the appropriate number' : "2\r"
          'press "c" to cancel' : "2\r"
